//go:build !genieql.ignore
// +build !genieql.ignore

package pkgb

import "time"

// DO NOT EDIT: This File was auto generated by the following command:
// genieql -test.testlogfile=/tmp/go-build3837374503/b493/testlog.txt -test.paniconexit0 -test.gocoverdir=/tmp/go-build3837374503/b493/gocoverdir -test.timeout=5m0s -test.coverprofile=/tmp/go-build3837374503/b493/_cover_.out

// PackageBExample generated by genieql
type PackageBExample struct {
	BoolField      bool
	Int4Array      []int
	Int8Array      []int
	TextField      string
	TimestampField time.Time
	UUIDArray      []string
	UUIDField      string
}
