package example

import (
	"net/netip"

	"github.com/james-lawrence/genieql/internal/sqlx"
)

// queryFunction2 generated by genieql
func queryFunction2(q sqlx.Queryer, query string, a netip.Prefix) ExampleRowScanner {
	return StaticExampleRowScanner(q.QueryRow(query, a))
}
