package example

import (
	"net"

	"bitbucket.org/jatone/genieql/internal/sqlx"
	"github.com/jackc/pgtype"
)

// queryFunction1 generated by genieql
func queryFunction1(q sqlx.Queryer, query string, a net.IPNet) ExampleScanner {
	var (
		c0 pgtype.CIDR
	)

	if err := c0.Set(a); err != nil {
		return StaticExampleScanner(nil, err)
	}

	return StaticExampleScanner(q.Query(query, c0))
}
