//go:build !genieql.ignore
// +build !genieql.ignore

package pkga

import (
	"net"
	"net/netip"
	"time"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto -o genieql.gen.go
// invoked by go generate @ pkga/pkga.go line 3

// Example1 generated by genieql
// Example1 ...
type Example1 struct {
	BigintField          int
	BoolField            bool
	CidrField            netip.Prefix
	DecimalField         float64
	DoublePrecisionField float64
	InetField            netip.Addr
	Int2Array            []int
	Int4Array            []int
	Int8Array            []int
	IntField             int
	IntervalField        time.Duration
	MacaddrField         net.HardwareAddr
	NumericField         float64
	RealField            float32
	SmallintField        int
	TextField            string
	TimestampField       time.Time
	UUIDArray            []string
	UUIDField            string
}
