//go:build !genieql.ignore
// +build !genieql.ignore

package pkga

import (
	"net"
	"time"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql -test.testlogfile=/var/folders/qv/04st9vg169b_4zvq86mv7kjw0000gn/T/go-build4247946028/b001/testlog.txt -test.paniconexit0 -test.v=true -test.run=^TestAutoGenerateConcurrent -test.timeout=3m0s

// Example1 generated by genieql
// Example1 ...
type Example1 struct {
	BigintField          int
	BitField             []byte
	BitVaryingField      []byte
	BoolField            bool
	ByteArrayField       []byte
	CharacterField       string
	CharacterFixedField  string
	CidrField            net.IPNet
	DecimalField         float64
	DoublePrecisionField float64
	InetField            net.IP
	Int2Array            []int
	Int4Array            []int
	Int8Array            []int
	IntField             int
	IntervalField        time.Duration
	JSONField            []byte
	JsonbField           []byte
	MacaddrField         net.HardwareAddr
	NumericField         float64
	RealField            float32
	SmallintField        int
	TextField            string
	TimestampField       time.Time
	UUIDArray            []string
	UUIDField            string
}


