package scanners

import (
	"database/sql"

	"github.com/lib/pq"
)

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql scanner dynamic --config=generators-test.config --output=type1_dynamic_scanner.gen.go bitbucket.org/jatone/genieql/generators/internal/scanners.Type1 type1
// invoked by go generate @ scanners/type1.go line 7

// NewType1DynamicScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewType1DynamicScannerDynamic(rows *sql.Rows, err error) Type1Scanner {
	if err != nil {
		return errType1Scanner{e: err}
	}

	return type1DynamicScannerDynamic{
		Rows: rows,
	}
}

type type1DynamicScannerDynamic struct {
	Rows *sql.Rows
}

func (t type1DynamicScannerDynamic) Scan(arg0 *Type1) error {
	const (
		field10 = "field1"
		field21 = "field2"
		field32 = "field3"
		field43 = "field4"
		field54 = "field5"
		field65 = "field6"
		field76 = "field7"
		field87 = "field8"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      sql.NullString
		c1      sql.NullString
		c2      sql.NullBool
		c3      sql.NullBool
		c4      sql.NullInt64
		c5      sql.NullInt64
		c6      pq.NullTime
		c7      pq.NullTime
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case field10:
			dst = append(dst, &c0)
		case field21:
			dst = append(dst, &c1)
		case field32:
			dst = append(dst, &c2)
		case field43:
			dst = append(dst, &c3)
		case field54:
			dst = append(dst, &c4)
		case field65:
			dst = append(dst, &c5)
		case field76:
			dst = append(dst, &c6)
		case field87:
			dst = append(dst, &c7)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case field10:
			if c0.Valid {
				tmp := c0.String
				arg0.Field1 = tmp
			}
		case field21:
			if c1.Valid {
				tmp := c1.String
				arg0.Field2 = &tmp
			}
		case field32:
			if c2.Valid {
				tmp := c2.Bool
				arg0.Field3 = tmp
			}
		case field43:
			if c3.Valid {
				tmp := c3.Bool
				arg0.Field4 = &tmp
			}
		case field54:
			if c4.Valid {
				tmp := int(c4.Int64)
				arg0.Field5 = tmp
			}
		case field65:
			if c5.Valid {
				tmp := int(c5.Int64)
				arg0.Field6 = &tmp
			}
		case field76:
			if c6.Valid {
				tmp := c6.Time
				arg0.Field7 = tmp
			}
		case field87:
			if c7.Valid {
				tmp := c7.Time
				arg0.Field8 = &tmp
			}
		}
	}

	return t.Rows.Err()
}

func (t type1DynamicScannerDynamic) Err() error {
	return t.Rows.Err()
}

func (t type1DynamicScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

func (t type1DynamicScannerDynamic) Next() bool {
	return t.Rows.Next()
}
