// +build !genieql.ignore

package autocompile

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql auto -o genieql.gen.go

import (
	"context"
	"database/sql"
	"net"
	"time"

	"bitbucket.org/jatone/genieql/internal/sqlx"
	"github.com/jackc/pgtype"
)

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql auto -vvvv -o genieql.gen.go

// Example1 structure generated by genieql.
type Example1 struct {
	BigintField          int
	BitField             []byte
	BitVaryingField      []byte
	BoolField            bool
	ByteArrayField       []byte
	CharacterField       string
	CharacterFixedField  string
	CidrField            net.IPNet
	DecimalField         float64
	DoublePrecisionField float64
	InetField            net.IP
	Int2Array            []int
	Int4Array            []int
	Int8Array            []int
	IntField             int
	IntervalField        time.Duration
	JSONField            []byte
	JsonbField           []byte
	MacaddrField         net.HardwareAddr
	NumericField         float64
	RealField            float32
	SmallintField        int
	TextField            string
	TimestampField       time.Time
	UUIDArray            []string
	UUIDField            string
}

// Example2 structure generated by genieql.
type Example2 struct {
	BoolField      bool
	Int4Array      []int
	Int8Array      []int
	TextField      string
	TimestampField time.Time
	UUIDArray      []string
	UUIDField      string
}

// Example3 structure generated by genieql.
type Example3 struct {
	BoolField      bool
	Int4Array      []int
	Int8Array      []int
	TextField      string
	TimestampField time.Time
	UUIDArray      []string
	UUIDField      string
}

// CustomScanner scanner interface.
type CustomScanner interface {
	Scan(i1, i2 *int, b1 *bool, t1 *time.Time) error
	Next() bool
	Close() error
	Err() error
}

type errCustomScanner struct {
	e error
}

func (t errCustomScanner) Scan(i1, i2 *int, b1 *bool, t1 *time.Time) error {
	return t.e
}

func (t errCustomScanner) Next() bool {
	return false
}

func (t errCustomScanner) Err() error {
	return t.e
}

func (t errCustomScanner) Close() error {
	return nil
}

// CustomScannerStaticColumns generated by genieql
const CustomScannerStaticColumns = `"i1","i2","b1","t1"`

// NewCustomScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewCustomScannerStatic(rows *sql.Rows, err error) CustomScanner {
	if err != nil {
		return errCustomScanner{e: err}
	}

	return customScannerStatic{
		Rows: rows,
	}
}

// customScannerStatic generated by genieql
type customScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t customScannerStatic) Scan(i1, i2 *int, b1 *bool, t1 *time.Time) error {
	var (
		c0 pgtype.Int8
		c1 pgtype.Int8
		c2 pgtype.Bool
		c3 pgtype.Timestamptz
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3); err != nil {
		return err
	}

	if err := c0.AssignTo(i1); err != nil {
		return err
	}

	if err := c1.AssignTo(i2); err != nil {
		return err
	}

	if err := c2.AssignTo(b1); err != nil {
		return err
	}

	if err := c3.AssignTo(t1); err != nil {
		return err
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t customScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t customScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t customScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewCustomScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewCustomScannerStaticRow(row *sql.Row) CustomScannerStaticRow {
	return CustomScannerStaticRow{
		row: row,
	}
}

// CustomScannerStaticRow generated by genieql
type CustomScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t CustomScannerStaticRow) Scan(i1, i2 *int, b1 *bool, t1 *time.Time) error {
	var (
		c0 pgtype.Int8
		c1 pgtype.Int8
		c2 pgtype.Bool
		c3 pgtype.Timestamptz
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3); err != nil {
		return err
	}

	if err := c0.AssignTo(i1); err != nil {
		return err
	}

	if err := c1.AssignTo(i2); err != nil {
		return err
	}

	if err := c2.AssignTo(b1); err != nil {
		return err
	}

	if err := c3.AssignTo(t1); err != nil {
		return err
	}

	return nil
}

// Err set an error to return by scan
func (t CustomScannerStaticRow) Err(err error) CustomScannerStaticRow {
	t.err = err
	return t
}

// NewCustomScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewCustomScannerDynamic(rows *sql.Rows, err error) CustomScanner {
	if err != nil {
		return errCustomScanner{e: err}
	}

	return customScannerDynamic{
		Rows: rows,
	}
}

// customScannerDynamic generated by genieql
type customScannerDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t customScannerDynamic) Scan(i1, i2 *int, b1 *bool, t1 *time.Time) error {
	const (
		cn0 = "i1"
		cn1 = "i2"
		cn2 = "b1"
		cn3 = "t1"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      pgtype.Int8
		c1      pgtype.Int8
		c2      pgtype.Bool
		c3      pgtype.Timestamptz
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if err := c0.AssignTo(i1); err != nil {
				return err
			}
		case cn1:
			if err := c1.AssignTo(i2); err != nil {
				return err
			}
		case cn2:
			if err := c2.AssignTo(b1); err != nil {
				return err
			}
		case cn3:
			if err := c3.AssignTo(t1); err != nil {
				return err
			}
		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t customScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t customScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t customScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// Example1Scanner scanner interface.
type Example1Scanner interface {
	Scan(sp0 *Example1) error
	Next() bool
	Close() error
	Err() error
}

type errExample1Scanner struct {
	e error
}

func (t errExample1Scanner) Scan(sp0 *Example1) error {
	return t.e
}

func (t errExample1Scanner) Next() bool {
	return false
}

func (t errExample1Scanner) Err() error {
	return t.e
}

func (t errExample1Scanner) Close() error {
	return nil
}

// Example1ScannerStaticColumns generated by genieql
const Example1ScannerStaticColumns = `"bigint_field","bit_field","bit_varying_field","bool_field","byte_array_field","character_field","character_fixed_field","cidr_field","decimal_field","double_precision_field","inet_field","int2_array","int4_array","int8_array","int_field","interval_field","json_field","jsonb_field","macaddr_field","numeric_field","real_field","smallint_field","text_field","timestamp_field","uuid_array","uuid_field"`

// NewExample1ScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewExample1ScannerStatic(rows *sql.Rows, err error) Example1Scanner {
	if err != nil {
		return errExample1Scanner{e: err}
	}

	return example1ScannerStatic{
		Rows: rows,
	}
}

// example1ScannerStatic generated by genieql
type example1ScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example1ScannerStatic) Scan(sp0 *Example1) error {
	var (
		c0  pgtype.Int8
		c1  pgtype.Bit
		c2  pgtype.Varbit
		c3  pgtype.Bool
		c4  pgtype.Bytea
		c5  pgtype.Varchar
		c6  pgtype.BPChar
		c7  pgtype.CIDR
		c8  pgtype.Numeric
		c9  pgtype.Float8
		c10 pgtype.Inet
		c11 pgtype.Int2Array
		c12 pgtype.Int4Array
		c13 pgtype.Int8Array
		c14 pgtype.Int4
		c15 pgtype.Interval
		c16 pgtype.JSON
		c17 pgtype.JSONB
		c18 pgtype.Macaddr
		c19 pgtype.Numeric
		c20 pgtype.Float4
		c21 pgtype.Int2
		c22 pgtype.Text
		c23 pgtype.Timestamptz
		c24 pgtype.UUIDArray
		c25 pgtype.UUID
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12, &c13, &c14, &c15, &c16, &c17, &c18, &c19, &c20, &c21, &c22, &c23, &c24, &c25); err != nil {
		return err
	}

	if err := c0.AssignTo(&sp0.BigintField); err != nil {
		return err
	}

	if err := c1.AssignTo(&sp0.BitField); err != nil {
		return err
	}

	if err := c2.AssignTo(&sp0.BitVaryingField); err != nil {
		return err
	}

	if err := c3.AssignTo(&sp0.BoolField); err != nil {
		return err
	}

	if err := c4.AssignTo(&sp0.ByteArrayField); err != nil {
		return err
	}

	if err := c5.AssignTo(&sp0.CharacterField); err != nil {
		return err
	}

	if err := c6.AssignTo(&sp0.CharacterFixedField); err != nil {
		return err
	}

	if err := c7.AssignTo(&sp0.CidrField); err != nil {
		return err
	}

	if err := c8.AssignTo(&sp0.DecimalField); err != nil {
		return err
	}

	if err := c9.AssignTo(&sp0.DoublePrecisionField); err != nil {
		return err
	}

	if err := c10.AssignTo(&sp0.InetField); err != nil {
		return err
	}

	if err := c11.AssignTo(&sp0.Int2Array); err != nil {
		return err
	}

	if err := c12.AssignTo(&sp0.Int4Array); err != nil {
		return err
	}

	if err := c13.AssignTo(&sp0.Int8Array); err != nil {
		return err
	}

	if err := c14.AssignTo(&sp0.IntField); err != nil {
		return err
	}

	if err := c15.AssignTo(&sp0.IntervalField); err != nil {
		return err
	}

	if err := c16.AssignTo(&sp0.JSONField); err != nil {
		return err
	}

	if err := c17.AssignTo(&sp0.JsonbField); err != nil {
		return err
	}

	if err := c18.AssignTo(&sp0.MacaddrField); err != nil {
		return err
	}

	if err := c19.AssignTo(&sp0.NumericField); err != nil {
		return err
	}

	if err := c20.AssignTo(&sp0.RealField); err != nil {
		return err
	}

	if err := c21.AssignTo(&sp0.SmallintField); err != nil {
		return err
	}

	if err := c22.AssignTo(&sp0.TextField); err != nil {
		return err
	}

	if err := c23.AssignTo(&sp0.TimestampField); err != nil {
		return err
	}

	if err := c24.AssignTo(&sp0.UUIDArray); err != nil {
		return err
	}

	if err := c25.AssignTo(&sp0.UUIDField); err != nil {
		return err
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example1ScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example1ScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example1ScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewExample1ScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewExample1ScannerStaticRow(row *sql.Row) Example1ScannerStaticRow {
	return Example1ScannerStaticRow{
		row: row,
	}
}

// Example1ScannerStaticRow generated by genieql
type Example1ScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t Example1ScannerStaticRow) Scan(sp0 *Example1) error {
	var (
		c0  pgtype.Int8
		c1  pgtype.Bit
		c2  pgtype.Varbit
		c3  pgtype.Bool
		c4  pgtype.Bytea
		c5  pgtype.Varchar
		c6  pgtype.BPChar
		c7  pgtype.CIDR
		c8  pgtype.Numeric
		c9  pgtype.Float8
		c10 pgtype.Inet
		c11 pgtype.Int2Array
		c12 pgtype.Int4Array
		c13 pgtype.Int8Array
		c14 pgtype.Int4
		c15 pgtype.Interval
		c16 pgtype.JSON
		c17 pgtype.JSONB
		c18 pgtype.Macaddr
		c19 pgtype.Numeric
		c20 pgtype.Float4
		c21 pgtype.Int2
		c22 pgtype.Text
		c23 pgtype.Timestamptz
		c24 pgtype.UUIDArray
		c25 pgtype.UUID
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12, &c13, &c14, &c15, &c16, &c17, &c18, &c19, &c20, &c21, &c22, &c23, &c24, &c25); err != nil {
		return err
	}

	if err := c0.AssignTo(&sp0.BigintField); err != nil {
		return err
	}

	if err := c1.AssignTo(&sp0.BitField); err != nil {
		return err
	}

	if err := c2.AssignTo(&sp0.BitVaryingField); err != nil {
		return err
	}

	if err := c3.AssignTo(&sp0.BoolField); err != nil {
		return err
	}

	if err := c4.AssignTo(&sp0.ByteArrayField); err != nil {
		return err
	}

	if err := c5.AssignTo(&sp0.CharacterField); err != nil {
		return err
	}

	if err := c6.AssignTo(&sp0.CharacterFixedField); err != nil {
		return err
	}

	if err := c7.AssignTo(&sp0.CidrField); err != nil {
		return err
	}

	if err := c8.AssignTo(&sp0.DecimalField); err != nil {
		return err
	}

	if err := c9.AssignTo(&sp0.DoublePrecisionField); err != nil {
		return err
	}

	if err := c10.AssignTo(&sp0.InetField); err != nil {
		return err
	}

	if err := c11.AssignTo(&sp0.Int2Array); err != nil {
		return err
	}

	if err := c12.AssignTo(&sp0.Int4Array); err != nil {
		return err
	}

	if err := c13.AssignTo(&sp0.Int8Array); err != nil {
		return err
	}

	if err := c14.AssignTo(&sp0.IntField); err != nil {
		return err
	}

	if err := c15.AssignTo(&sp0.IntervalField); err != nil {
		return err
	}

	if err := c16.AssignTo(&sp0.JSONField); err != nil {
		return err
	}

	if err := c17.AssignTo(&sp0.JsonbField); err != nil {
		return err
	}

	if err := c18.AssignTo(&sp0.MacaddrField); err != nil {
		return err
	}

	if err := c19.AssignTo(&sp0.NumericField); err != nil {
		return err
	}

	if err := c20.AssignTo(&sp0.RealField); err != nil {
		return err
	}

	if err := c21.AssignTo(&sp0.SmallintField); err != nil {
		return err
	}

	if err := c22.AssignTo(&sp0.TextField); err != nil {
		return err
	}

	if err := c23.AssignTo(&sp0.TimestampField); err != nil {
		return err
	}

	if err := c24.AssignTo(&sp0.UUIDArray); err != nil {
		return err
	}

	if err := c25.AssignTo(&sp0.UUIDField); err != nil {
		return err
	}

	return nil
}

// Err set an error to return by scan
func (t Example1ScannerStaticRow) Err(err error) Example1ScannerStaticRow {
	t.err = err
	return t
}

// NewExample1ScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewExample1ScannerDynamic(rows *sql.Rows, err error) Example1Scanner {
	if err != nil {
		return errExample1Scanner{e: err}
	}

	return example1ScannerDynamic{
		Rows: rows,
	}
}

// example1ScannerDynamic generated by genieql
type example1ScannerDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example1ScannerDynamic) Scan(sp0 *Example1) error {
	const (
		cn0  = "bigint_field"
		cn1  = "bit_field"
		cn2  = "bit_varying_field"
		cn3  = "bool_field"
		cn4  = "byte_array_field"
		cn5  = "character_field"
		cn6  = "character_fixed_field"
		cn7  = "cidr_field"
		cn8  = "decimal_field"
		cn9  = "double_precision_field"
		cn10 = "inet_field"
		cn11 = "int2_array"
		cn12 = "int4_array"
		cn13 = "int8_array"
		cn14 = "int_field"
		cn15 = "interval_field"
		cn16 = "json_field"
		cn17 = "jsonb_field"
		cn18 = "macaddr_field"
		cn19 = "numeric_field"
		cn20 = "real_field"
		cn21 = "smallint_field"
		cn22 = "text_field"
		cn23 = "timestamp_field"
		cn24 = "uuid_array"
		cn25 = "uuid_field"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      pgtype.Int8
		c1      pgtype.Bit
		c2      pgtype.Varbit
		c3      pgtype.Bool
		c4      pgtype.Bytea
		c5      pgtype.Varchar
		c6      pgtype.BPChar
		c7      pgtype.CIDR
		c8      pgtype.Numeric
		c9      pgtype.Float8
		c10     pgtype.Inet
		c11     pgtype.Int2Array
		c12     pgtype.Int4Array
		c13     pgtype.Int8Array
		c14     pgtype.Int4
		c15     pgtype.Interval
		c16     pgtype.JSON
		c17     pgtype.JSONB
		c18     pgtype.Macaddr
		c19     pgtype.Numeric
		c20     pgtype.Float4
		c21     pgtype.Int2
		c22     pgtype.Text
		c23     pgtype.Timestamptz
		c24     pgtype.UUIDArray
		c25     pgtype.UUID
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		case cn7:
			dst = append(dst, &c7)
		case cn8:
			dst = append(dst, &c8)
		case cn9:
			dst = append(dst, &c9)
		case cn10:
			dst = append(dst, &c10)
		case cn11:
			dst = append(dst, &c11)
		case cn12:
			dst = append(dst, &c12)
		case cn13:
			dst = append(dst, &c13)
		case cn14:
			dst = append(dst, &c14)
		case cn15:
			dst = append(dst, &c15)
		case cn16:
			dst = append(dst, &c16)
		case cn17:
			dst = append(dst, &c17)
		case cn18:
			dst = append(dst, &c18)
		case cn19:
			dst = append(dst, &c19)
		case cn20:
			dst = append(dst, &c20)
		case cn21:
			dst = append(dst, &c21)
		case cn22:
			dst = append(dst, &c22)
		case cn23:
			dst = append(dst, &c23)
		case cn24:
			dst = append(dst, &c24)
		case cn25:
			dst = append(dst, &c25)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if err := c0.AssignTo(&sp0.BigintField); err != nil {
				return err
			}
		case cn1:
			if err := c1.AssignTo(&sp0.BitField); err != nil {
				return err
			}
		case cn2:
			if err := c2.AssignTo(&sp0.BitVaryingField); err != nil {
				return err
			}
		case cn3:
			if err := c3.AssignTo(&sp0.BoolField); err != nil {
				return err
			}
		case cn4:
			if err := c4.AssignTo(&sp0.ByteArrayField); err != nil {
				return err
			}
		case cn5:
			if err := c5.AssignTo(&sp0.CharacterField); err != nil {
				return err
			}
		case cn6:
			if err := c6.AssignTo(&sp0.CharacterFixedField); err != nil {
				return err
			}
		case cn7:
			if err := c7.AssignTo(&sp0.CidrField); err != nil {
				return err
			}
		case cn8:
			if err := c8.AssignTo(&sp0.DecimalField); err != nil {
				return err
			}
		case cn9:
			if err := c9.AssignTo(&sp0.DoublePrecisionField); err != nil {
				return err
			}
		case cn10:
			if err := c10.AssignTo(&sp0.InetField); err != nil {
				return err
			}
		case cn11:
			if err := c11.AssignTo(&sp0.Int2Array); err != nil {
				return err
			}
		case cn12:
			if err := c12.AssignTo(&sp0.Int4Array); err != nil {
				return err
			}
		case cn13:
			if err := c13.AssignTo(&sp0.Int8Array); err != nil {
				return err
			}
		case cn14:
			if err := c14.AssignTo(&sp0.IntField); err != nil {
				return err
			}
		case cn15:
			if err := c15.AssignTo(&sp0.IntervalField); err != nil {
				return err
			}
		case cn16:
			if err := c16.AssignTo(&sp0.JSONField); err != nil {
				return err
			}
		case cn17:
			if err := c17.AssignTo(&sp0.JsonbField); err != nil {
				return err
			}
		case cn18:
			if err := c18.AssignTo(&sp0.MacaddrField); err != nil {
				return err
			}
		case cn19:
			if err := c19.AssignTo(&sp0.NumericField); err != nil {
				return err
			}
		case cn20:
			if err := c20.AssignTo(&sp0.RealField); err != nil {
				return err
			}
		case cn21:
			if err := c21.AssignTo(&sp0.SmallintField); err != nil {
				return err
			}
		case cn22:
			if err := c22.AssignTo(&sp0.TextField); err != nil {
				return err
			}
		case cn23:
			if err := c23.AssignTo(&sp0.TimestampField); err != nil {
				return err
			}
		case cn24:
			if err := c24.AssignTo(&sp0.UUIDArray); err != nil {
				return err
			}
		case cn25:
			if err := c25.AssignTo(&sp0.UUIDField); err != nil {
				return err
			}
		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example1ScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example1ScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example1ScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// Example2Scanner scanner interface.
type Example2Scanner interface {
	Scan(sp0 *Example2) error
	Next() bool
	Close() error
	Err() error
}

type errExample2Scanner struct {
	e error
}

func (t errExample2Scanner) Scan(sp0 *Example2) error {
	return t.e
}

func (t errExample2Scanner) Next() bool {
	return false
}

func (t errExample2Scanner) Err() error {
	return t.e
}

func (t errExample2Scanner) Close() error {
	return nil
}

// Example2ScannerStaticColumns generated by genieql
const Example2ScannerStaticColumns = `"bool_field","int4_array","int8_array","text_field","timestamp_field","uuid_array","uuid_field"`

// NewExample2ScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewExample2ScannerStatic(rows *sql.Rows, err error) Example2Scanner {
	if err != nil {
		return errExample2Scanner{e: err}
	}

	return example2ScannerStatic{
		Rows: rows,
	}
}

// example2ScannerStatic generated by genieql
type example2ScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example2ScannerStatic) Scan(sp0 *Example2) error {
	var (
		c0 pgtype.Bool
		c1 pgtype.Int4Array
		c2 pgtype.Int8Array
		c3 pgtype.Text
		c4 pgtype.Timestamptz
		c5 pgtype.UUIDArray
		c6 pgtype.UUID
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	if err := c0.AssignTo(&sp0.BoolField); err != nil {
		return err
	}

	if err := c1.AssignTo(&sp0.Int4Array); err != nil {
		return err
	}

	if err := c2.AssignTo(&sp0.Int8Array); err != nil {
		return err
	}

	if err := c3.AssignTo(&sp0.TextField); err != nil {
		return err
	}

	if err := c4.AssignTo(&sp0.TimestampField); err != nil {
		return err
	}

	if err := c5.AssignTo(&sp0.UUIDArray); err != nil {
		return err
	}

	if err := c6.AssignTo(&sp0.UUIDField); err != nil {
		return err
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example2ScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example2ScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example2ScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewExample2ScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewExample2ScannerStaticRow(row *sql.Row) Example2ScannerStaticRow {
	return Example2ScannerStaticRow{
		row: row,
	}
}

// Example2ScannerStaticRow generated by genieql
type Example2ScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t Example2ScannerStaticRow) Scan(sp0 *Example2) error {
	var (
		c0 pgtype.Bool
		c1 pgtype.Int4Array
		c2 pgtype.Int8Array
		c3 pgtype.Text
		c4 pgtype.Timestamptz
		c5 pgtype.UUIDArray
		c6 pgtype.UUID
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6); err != nil {
		return err
	}

	if err := c0.AssignTo(&sp0.BoolField); err != nil {
		return err
	}

	if err := c1.AssignTo(&sp0.Int4Array); err != nil {
		return err
	}

	if err := c2.AssignTo(&sp0.Int8Array); err != nil {
		return err
	}

	if err := c3.AssignTo(&sp0.TextField); err != nil {
		return err
	}

	if err := c4.AssignTo(&sp0.TimestampField); err != nil {
		return err
	}

	if err := c5.AssignTo(&sp0.UUIDArray); err != nil {
		return err
	}

	if err := c6.AssignTo(&sp0.UUIDField); err != nil {
		return err
	}

	return nil
}

// Err set an error to return by scan
func (t Example2ScannerStaticRow) Err(err error) Example2ScannerStaticRow {
	t.err = err
	return t
}

// NewExample2ScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewExample2ScannerDynamic(rows *sql.Rows, err error) Example2Scanner {
	if err != nil {
		return errExample2Scanner{e: err}
	}

	return example2ScannerDynamic{
		Rows: rows,
	}
}

// example2ScannerDynamic generated by genieql
type example2ScannerDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example2ScannerDynamic) Scan(sp0 *Example2) error {
	const (
		cn0 = "bool_field"
		cn1 = "int4_array"
		cn2 = "int8_array"
		cn3 = "text_field"
		cn4 = "timestamp_field"
		cn5 = "uuid_array"
		cn6 = "uuid_field"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      pgtype.Bool
		c1      pgtype.Int4Array
		c2      pgtype.Int8Array
		c3      pgtype.Text
		c4      pgtype.Timestamptz
		c5      pgtype.UUIDArray
		c6      pgtype.UUID
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if err := c0.AssignTo(&sp0.BoolField); err != nil {
				return err
			}
		case cn1:
			if err := c1.AssignTo(&sp0.Int4Array); err != nil {
				return err
			}
		case cn2:
			if err := c2.AssignTo(&sp0.Int8Array); err != nil {
				return err
			}
		case cn3:
			if err := c3.AssignTo(&sp0.TextField); err != nil {
				return err
			}
		case cn4:
			if err := c4.AssignTo(&sp0.TimestampField); err != nil {
				return err
			}
		case cn5:
			if err := c5.AssignTo(&sp0.UUIDArray); err != nil {
				return err
			}
		case cn6:
			if err := c6.AssignTo(&sp0.UUIDField); err != nil {
				return err
			}
		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example2ScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example2ScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example2ScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// CombinedScanner scanner interface.
type CombinedScanner interface {
	Scan(e1 *Example1, e2 *Example2) error
	Next() bool
	Close() error
	Err() error
}

type errCombinedScanner struct {
	e error
}

func (t errCombinedScanner) Scan(e1 *Example1, e2 *Example2) error {
	return t.e
}

func (t errCombinedScanner) Next() bool {
	return false
}

func (t errCombinedScanner) Err() error {
	return t.e
}

func (t errCombinedScanner) Close() error {
	return nil
}

// NewCombinedScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewCombinedScannerStatic(rows *sql.Rows, err error) CombinedScanner {
	if err != nil {
		return errCombinedScanner{e: err}
	}

	return combinedScannerStatic{
		Rows: rows,
	}
}

// combinedScannerStatic generated by genieql
type combinedScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t combinedScannerStatic) Scan(e1 *Example1, e2 *Example2) error {
	var (
		c0  pgtype.Int8
		c1  pgtype.Bit
		c2  pgtype.Varbit
		c3  pgtype.Bool
		c4  pgtype.Bytea
		c5  pgtype.Varchar
		c6  pgtype.BPChar
		c7  pgtype.CIDR
		c8  pgtype.Numeric
		c9  pgtype.Float8
		c10 pgtype.Inet
		c11 pgtype.Int2Array
		c12 pgtype.Int4Array
		c13 pgtype.Int8Array
		c14 pgtype.Int4
		c15 pgtype.Interval
		c16 pgtype.JSON
		c17 pgtype.JSONB
		c18 pgtype.Macaddr
		c19 pgtype.Numeric
		c20 pgtype.Float4
		c21 pgtype.Int2
		c22 pgtype.Text
		c23 pgtype.Timestamptz
		c24 pgtype.UUIDArray
		c25 pgtype.UUID
		c26 pgtype.Bool
		c27 pgtype.Int4Array
		c28 pgtype.Int8Array
		c29 pgtype.Text
		c30 pgtype.Timestamptz
		c31 pgtype.UUIDArray
		c32 pgtype.UUID
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12, &c13, &c14, &c15, &c16, &c17, &c18, &c19, &c20, &c21, &c22, &c23, &c24, &c25, &c26, &c27, &c28, &c29, &c30, &c31, &c32); err != nil {
		return err
	}

	if err := c0.AssignTo(&e1.BigintField); err != nil {
		return err
	}

	if err := c1.AssignTo(&e1.BitField); err != nil {
		return err
	}

	if err := c2.AssignTo(&e1.BitVaryingField); err != nil {
		return err
	}

	if err := c3.AssignTo(&e1.BoolField); err != nil {
		return err
	}

	if err := c4.AssignTo(&e1.ByteArrayField); err != nil {
		return err
	}

	if err := c5.AssignTo(&e1.CharacterField); err != nil {
		return err
	}

	if err := c6.AssignTo(&e1.CharacterFixedField); err != nil {
		return err
	}

	if err := c7.AssignTo(&e1.CidrField); err != nil {
		return err
	}

	if err := c8.AssignTo(&e1.DecimalField); err != nil {
		return err
	}

	if err := c9.AssignTo(&e1.DoublePrecisionField); err != nil {
		return err
	}

	if err := c10.AssignTo(&e1.InetField); err != nil {
		return err
	}

	if err := c11.AssignTo(&e1.Int2Array); err != nil {
		return err
	}

	if err := c12.AssignTo(&e1.Int4Array); err != nil {
		return err
	}

	if err := c13.AssignTo(&e1.Int8Array); err != nil {
		return err
	}

	if err := c14.AssignTo(&e1.IntField); err != nil {
		return err
	}

	if err := c15.AssignTo(&e1.IntervalField); err != nil {
		return err
	}

	if err := c16.AssignTo(&e1.JSONField); err != nil {
		return err
	}

	if err := c17.AssignTo(&e1.JsonbField); err != nil {
		return err
	}

	if err := c18.AssignTo(&e1.MacaddrField); err != nil {
		return err
	}

	if err := c19.AssignTo(&e1.NumericField); err != nil {
		return err
	}

	if err := c20.AssignTo(&e1.RealField); err != nil {
		return err
	}

	if err := c21.AssignTo(&e1.SmallintField); err != nil {
		return err
	}

	if err := c22.AssignTo(&e1.TextField); err != nil {
		return err
	}

	if err := c23.AssignTo(&e1.TimestampField); err != nil {
		return err
	}

	if err := c24.AssignTo(&e1.UUIDArray); err != nil {
		return err
	}

	if err := c25.AssignTo(&e1.UUIDField); err != nil {
		return err
	}

	if err := c26.AssignTo(&e2.BoolField); err != nil {
		return err
	}

	if err := c27.AssignTo(&e2.Int4Array); err != nil {
		return err
	}

	if err := c28.AssignTo(&e2.Int8Array); err != nil {
		return err
	}

	if err := c29.AssignTo(&e2.TextField); err != nil {
		return err
	}

	if err := c30.AssignTo(&e2.TimestampField); err != nil {
		return err
	}

	if err := c31.AssignTo(&e2.UUIDArray); err != nil {
		return err
	}

	if err := c32.AssignTo(&e2.UUIDField); err != nil {
		return err
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t combinedScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t combinedScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t combinedScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewCombinedScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewCombinedScannerStaticRow(row *sql.Row) CombinedScannerStaticRow {
	return CombinedScannerStaticRow{
		row: row,
	}
}

// CombinedScannerStaticRow generated by genieql
type CombinedScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t CombinedScannerStaticRow) Scan(e1 *Example1, e2 *Example2) error {
	var (
		c0  pgtype.Int8
		c1  pgtype.Bit
		c2  pgtype.Varbit
		c3  pgtype.Bool
		c4  pgtype.Bytea
		c5  pgtype.Varchar
		c6  pgtype.BPChar
		c7  pgtype.CIDR
		c8  pgtype.Numeric
		c9  pgtype.Float8
		c10 pgtype.Inet
		c11 pgtype.Int2Array
		c12 pgtype.Int4Array
		c13 pgtype.Int8Array
		c14 pgtype.Int4
		c15 pgtype.Interval
		c16 pgtype.JSON
		c17 pgtype.JSONB
		c18 pgtype.Macaddr
		c19 pgtype.Numeric
		c20 pgtype.Float4
		c21 pgtype.Int2
		c22 pgtype.Text
		c23 pgtype.Timestamptz
		c24 pgtype.UUIDArray
		c25 pgtype.UUID
		c26 pgtype.Bool
		c27 pgtype.Int4Array
		c28 pgtype.Int8Array
		c29 pgtype.Text
		c30 pgtype.Timestamptz
		c31 pgtype.UUIDArray
		c32 pgtype.UUID
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12, &c13, &c14, &c15, &c16, &c17, &c18, &c19, &c20, &c21, &c22, &c23, &c24, &c25, &c26, &c27, &c28, &c29, &c30, &c31, &c32); err != nil {
		return err
	}

	if err := c0.AssignTo(&e1.BigintField); err != nil {
		return err
	}

	if err := c1.AssignTo(&e1.BitField); err != nil {
		return err
	}

	if err := c2.AssignTo(&e1.BitVaryingField); err != nil {
		return err
	}

	if err := c3.AssignTo(&e1.BoolField); err != nil {
		return err
	}

	if err := c4.AssignTo(&e1.ByteArrayField); err != nil {
		return err
	}

	if err := c5.AssignTo(&e1.CharacterField); err != nil {
		return err
	}

	if err := c6.AssignTo(&e1.CharacterFixedField); err != nil {
		return err
	}

	if err := c7.AssignTo(&e1.CidrField); err != nil {
		return err
	}

	if err := c8.AssignTo(&e1.DecimalField); err != nil {
		return err
	}

	if err := c9.AssignTo(&e1.DoublePrecisionField); err != nil {
		return err
	}

	if err := c10.AssignTo(&e1.InetField); err != nil {
		return err
	}

	if err := c11.AssignTo(&e1.Int2Array); err != nil {
		return err
	}

	if err := c12.AssignTo(&e1.Int4Array); err != nil {
		return err
	}

	if err := c13.AssignTo(&e1.Int8Array); err != nil {
		return err
	}

	if err := c14.AssignTo(&e1.IntField); err != nil {
		return err
	}

	if err := c15.AssignTo(&e1.IntervalField); err != nil {
		return err
	}

	if err := c16.AssignTo(&e1.JSONField); err != nil {
		return err
	}

	if err := c17.AssignTo(&e1.JsonbField); err != nil {
		return err
	}

	if err := c18.AssignTo(&e1.MacaddrField); err != nil {
		return err
	}

	if err := c19.AssignTo(&e1.NumericField); err != nil {
		return err
	}

	if err := c20.AssignTo(&e1.RealField); err != nil {
		return err
	}

	if err := c21.AssignTo(&e1.SmallintField); err != nil {
		return err
	}

	if err := c22.AssignTo(&e1.TextField); err != nil {
		return err
	}

	if err := c23.AssignTo(&e1.TimestampField); err != nil {
		return err
	}

	if err := c24.AssignTo(&e1.UUIDArray); err != nil {
		return err
	}

	if err := c25.AssignTo(&e1.UUIDField); err != nil {
		return err
	}

	if err := c26.AssignTo(&e2.BoolField); err != nil {
		return err
	}

	if err := c27.AssignTo(&e2.Int4Array); err != nil {
		return err
	}

	if err := c28.AssignTo(&e2.Int8Array); err != nil {
		return err
	}

	if err := c29.AssignTo(&e2.TextField); err != nil {
		return err
	}

	if err := c30.AssignTo(&e2.TimestampField); err != nil {
		return err
	}

	if err := c31.AssignTo(&e2.UUIDArray); err != nil {
		return err
	}

	if err := c32.AssignTo(&e2.UUIDField); err != nil {
		return err
	}

	return nil
}

// Err set an error to return by scan
func (t CombinedScannerStaticRow) Err(err error) CombinedScannerStaticRow {
	t.err = err
	return t
}

// Example1FindByX1 generates function
func Example1FindByX1(ctx context.Context, q sqlx.Queryer, i1, i2 int) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bit_field","bit_varying_field","bool_field","byte_array_field","character_field","character_fixed_field","cidr_field","decimal_field","double_precision_field","inet_field","int2_array","int4_array","int8_array","int_field","interval_field","json_field","jsonb_field","macaddr_field","numeric_field","real_field","smallint_field","text_field","timestamp_field","uuid_array","uuid_field" FROM example1 WHERE id = $1 AND foo = $2`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, i1, i2))
}
