package alternate1

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql generate insert experimental batch-function --config=generators-test.config -o postgresql.insert.batch.gen.go
// invoked by go generate @ alternate1/10_genieql.go line 7
