FROM ubuntu:noble
ARG DEBIAN_FRONTEND=noninteractive
ARG GOBIN=/usr/local/bin

RUN apt-get update
RUN apt-get -y install software-properties-common build-essential apt-file curl apt-transport-https
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb
RUN apt-get update
RUN apt-get -y install dput devscripts dh-make dput git uidmap dbus-user-session fuse-overlayfs
RUN apt-get -y install golang-1.23 podman rsync vim eg dpkg tree pinentry-tty
RUN apt-get -y install postgresql postgresql-client postgresql-contrib postgresql-client-common
RUN ln -s /usr/lib/go-1.23/bin/go /usr/local/bin/go
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
RUN go install github.com/james-lawrence/genieql/...@latest
RUN echo "local all all trust\nhost all all 127.0.0.1/32 trust" > /etc/postgresql/16/main/pg_hba.conf
RUN systemctl enable postgresql

CMD /usr/sbin/init
