FROM ubuntu:noble
ARG DEBIAN_FRONTEND=noninteractive
ARG GOBIN=/usr/local/bin

RUN apt-get update
RUN apt-get install -y software-properties-common build-essential apt-file curl apt-transport-https
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb
RUN apt-get update
RUN apt-get install -y dput devscripts dh-make dput git uidmap dbus-user-session fuse-overlayfs
RUN apt-get install -y golang-1.23 podman rsync vim dpkg tree pinentry-tty
RUN apt-get install -y postgresql postgresql-client postgresql-contrib postgresql-client-common
RUN apt-get install -o Acquire::ForceIPv4=true -y eg duckdb
RUN ln -s /usr/lib/go-1.23/bin/go /usr/local/bin/go
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
RUN systemctl enable postgresql

CMD /usr/sbin/init
