// Package genieql generates code to interact with a database.
package genieql

import (
	"go/token"
	"io"
)

// Preface text inserted at the top of all generated files.
const Preface = `

// DO NOT MODIFY: This File was auto generated by genieql.
// genieql %s

`

// ScannerGenerator interface for scanner generators.
type ScannerGenerator interface {
	Scanner(dst io.Writer, fset *token.FileSet) error
}
