// Package genieql generates code to interact with a database.
package genieql

import (
	"bytes"
	"go/format"
	"go/token"
	"io"

	"golang.org/x/tools/imports"
)

// Preface text inserted at the top of all generated files.
const Preface = `

// DO NOT MODIFY: This File was auto generated by genieql.
// genieql %s

`

// ScannerGenerator interface for scanner generators.
type ScannerGenerator interface {
	Scanner(dst io.Writer, fset *token.FileSet) error
}

func FormatOutput(raw []byte) (io.Reader, error) {
	var err error
	if raw, err = imports.Process("", raw, nil); err != nil {
		return bytes.NewReader(raw), err
	}

	if raw, err = format.Source(raw); err != nil {
		return bytes.NewReader(raw), err
	}

	return bytes.NewReader(raw), err
}
