package main

import (
	"database/sql"
	"io"
)

// DO NOT MODIFY: This File was auto generated by genieql.
// genieql scanner query-literal --output=example_query_literal_gen.go CrudScanner bitbucket.org/jatone/genieql/examples/scanners/query-literal.example bitbucket.org/jatone/genieql/examples/scanners/query-literal.myQuery

type CrudScanner interface {
	Scan(arg0 *example) error
	Close() error
	Err() error
}

type crudscanner struct {
	rows *sql.Rows
}

func (t crudscanner) Scan(arg0 *example) error {
	if !t.rows.Next() {
		return io.EOF
	}
	if err := t.rows.Scan(); err != nil {
		return err
	}
	return t.rows.Err()
}
func (t crudscanner) Err() error {
	return t.rows.Err()
}
func (t crudscanner) Close() error {
	if t.rows == nil {
		return nil
	}
	return t.rows.Close()
}

type errCrudScanner struct {
	err error
}

func (t errCrudScanner) Scan(arg0 *example) error {
	return t.err
}
func (t errCrudScanner) Err() error {
	return t.err
}
func (t errCrudScanner) Close() error {
	return nil
}
