package example

import (
	"database/sql"

	"bitbucket.org/jatone/genieql/internal/sqlx"
)

// queryFunction10 generated by genieql
func queryFunction10(q sqlx.Queryer, query int) ExampleScanner {
	const queryFunction10Query = `SELECT * FROM example WHERE id = $1`
	var (
		c0 sql.NullInt64
	)

	c0.Int64 = int64(query)

	return StaticExampleScanner(q.Query(queryFunction10Query, c0))
}
