package example

import (
	"database/sql"

	"bitbucket.org/jatone/genieql/internal/sqlx"
)

// queryFunction11 generated by genieql
func queryFunction11(q sqlx.Queryer, query string, _type int, _func int) ExampleRowScanner {
	var (
		c0 sql.NullInt64
		c1 sql.NullInt64
	)

	c0.Int64 = int64(_type)
	c1.Int64 = int64(_func)

	return StaticExampleRowScanner(q.QueryRow(query, c0, c1))
}
