//go:build !genieql.ignore
// +build !genieql.ignore

package pkgb

import "time"

// DO NOT EDIT: This File was auto generated by the following command:
// genieql -test.testlogfile=/var/folders/qv/04st9vg169b_4zvq86mv7kjw0000gn/T/go-build3643822935/b001/testlog.txt -test.paniconexit0 -test.v=true -test.run=TestAutoCompileGraph_Integration_ThreeLevelDependencies -test.timeout=30s

// PackageBExample generated by genieql
type PackageBExample struct {
	BoolField      bool
	Int4Array      []int
	Int8Array      []int
	TextField      string
	TimestampField time.Time
	UUIDArray      []string
	UUIDField      string
}


