//go:build !genieql.ignore
// +build !genieql.ignore

package pkgb

import "time"

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto graph --config=postgresql.test.config -o genieql.gen.go

// PackageBExample generated by genieql
type PackageBExample struct {
	BoolField      bool
	Int4Array      []int
	Int8Array      []int
	TextField      string
	TimestampField time.Time
	UUIDArray      []string
	UUIDField      string
}


