package example

import "time"

// MyStruct structure generated by genieql.
type MyStruct struct {
	Field1        string
	Field2        *string
	Field3        bool
	Field4        *bool
	Field5        int
	Field6        *int
	Field7        time.Time
	Field8        *time.Time
	Unmappedfield int
}
