package definitions

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql generate experimental structure query constants -o postgresql.query.structs.gen.go
// invoked by go generate @ definitions/example.go line 4

// QueryExample1 generated by genieql
type QueryExample1 struct {
	UUIDField string
}

// QueryExample2 generated by genieql
type QueryExample2 struct {
	UUIDField string
}
