package definitions

import "bitbucket.org/jatone/genieql/sqlx"

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql generate experimental functions types -o postgresql.functions.gen.go
// invoked by go generate @ definitions/example.go line 7

func customQueryFunction(q sqlx.Queryer, query string, x1, x2, x3 int) ProfileScanner {
	return NewProfileScannerDynamic(q.Query(query, x1, x2, x3))
}

func customQueryFucntion2(q sqlx.Queryer, x1, x2, x3 int) ProfileScanner {
	var query = query1
	return NewProfileScannerDynamic(q.Query(query, x1, x2, x3))
}
