package generators_test

import (
	"bytes"

	"bitbucket.org/jatone/genieql"

	. "bitbucket.org/jatone/genieql/generators"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("ColumnConstants", func() {
	ginkgo.DescribeTable("should create a constant based on the table details",
		func(name string, columns []genieql.ColumnInfo, trans genieql.ColumnTransformer, result string) {
			dst := bytes.NewBuffer([]byte{})
			Expect(NewColumnConstants(name, trans, columns).Generate(dst)).ToNot(HaveOccurred())
			Expect(dst.String()).To(Equal(result))
		},
		ginkgo.Entry(
			"simple columns",
			"constant",
			[]genieql.ColumnInfo{
				{
					Name: "col1",
				},
				{
					Name: "col2",
				},
			},
			genieql.NewColumnInfoNameTransformer(""),
			"\n// constant generated by genieql\nconst constant = `col1,col2`\n",
		),
	)
})
