package generators_test

import (
	"bytes"

	"github.com/james-lawrence/genieql"
	"golang.org/x/text/transform"

	"github.com/james-lawrence/genieql/columninfo"
	. "github.com/james-lawrence/genieql/generators"
	"github.com/james-lawrence/genieql/internal/transformx"

	"github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = ginkgo.Describe("ColumnConstants", func() {
	ginkgo.DescribeTable("should create a constant based on the table details",
		func(name string, columns []genieql.ColumnInfo, trans genieql.ColumnTransformer, result string) {
			dst := bytes.NewBuffer([]byte{})
			Expect(NewColumnConstants(name, trans, columns).Generate(dst)).ToNot(HaveOccurred())
			Expect(dst.String()).To(Equal(result))
		},
		ginkgo.Entry(
			"simple columns",
			"constant",
			[]genieql.ColumnInfo{
				{
					Name: "col1",
				},
				{
					Name: "col2",
				},
			},
			columninfo.NewNameTransformer(transform.Nop),
			"\n// constant generated by genieql\nconst constant = `col1,col2`\n",
		),
		ginkgo.Entry(
			"with prefix",
			"constant",
			[]genieql.ColumnInfo{
				{
					Name: "col1",
				},
				{
					Name: "col2",
				},
			},
			columninfo.NewNameTransformer(
				transformx.Wrap("\""),
				transformx.Prefix("\"foo\"."),
			),
			"\n// constant generated by genieql\nconst constant = `\"foo\".\"col1\",\"foo\".\"col2\"`\n",
		),
	)
})
