//go:build !genieql.ignore
// +build !genieql.ignore

package duckdb

import (
	"context"
	"database/sql"
	"math"
	"time"

	"github.com/gofrs/uuid"
	"github.com/james-lawrence/genieql/ducktype"
	"github.com/james-lawrence/genieql/internal/sqlx"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto --config duckdb.example.config -o genieql.gen.go
// invoked by go generate @ duckdb/duckdb.go line 6

// Example1 generated by genieql
// Example1 ...
type Example1 struct {
	BigintField          int64
	BoolField            bool
	ByteArrayField       []byte
	DoublePrecisionField float64
	Int2Field            int16
	IntField             int32
	RealField            float32
	SmallintField        int16
	TextField            string
	TimestampField       time.Time
	UbigintField         uint64
	UintegerField        uint32
	UUIDField            string
}

// Example1Scanner scanner interface.
type Example1Scanner interface {
	Scan(sp0 *Example1) error
	Next() bool
	Close() error
	Err() error
}

type errExample1Scanner struct {
	e error
}

func (t errExample1Scanner) Scan(sp0 *Example1) error {
	return t.e
}

func (t errExample1Scanner) Next() bool {
	return false
}

func (t errExample1Scanner) Err() error {
	return t.e
}

func (t errExample1Scanner) Close() error {
	return nil
}

// Example1ScannerStaticColumns generated by genieql
const Example1ScannerStaticColumns = `"bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field"`

// NewExample1ScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewExample1ScannerStatic(rows *sql.Rows, err error) Example1Scanner {
	if err != nil {
		return errExample1Scanner{e: err}
	}

	return example1ScannerStatic{
		Rows: rows,
	}
}

// example1ScannerStatic generated by genieql
type example1ScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example1ScannerStatic) Scan(sp0 *Example1) error {
	var (
		c0  sql.NullInt64
		c1  sql.NullBool
		c2  []byte
		c3  sql.NullFloat64
		c4  sql.NullInt16
		c5  sql.NullInt32
		c6  sql.NullFloat64
		c7  sql.NullInt16
		c8  sql.NullString
		c9  ducktype.NullTime
		c10 ducktype.NullUint64
		c11 sql.NullInt64
		c12 sql.NullString
	)

	if err := t.Rows.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12); err != nil {
		return err
	}

	if c0.Valid {
		tmp := int64(c0.Int64)
		sp0.BigintField = tmp
	}

	if c1.Valid {
		tmp := c1.Bool
		sp0.BoolField = tmp
	}

	sp0.ByteArrayField = c2

	if c3.Valid {
		tmp := float64(c3.Float64)
		sp0.DoublePrecisionField = tmp
	}

	if c4.Valid {
		tmp := int16(c4.Int16)
		sp0.Int2Field = tmp
	}

	if c5.Valid {
		tmp := int32(c5.Int32)
		sp0.IntField = tmp
	}

	if c6.Valid {
		tmp := float32(c6.Float64)
		sp0.RealField = tmp
	}

	if c7.Valid {
		tmp := int16(c7.Int16)
		sp0.SmallintField = tmp
	}

	if c8.Valid {
		tmp := string(c8.String)
		sp0.TextField = tmp
	}

	switch c9.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		sp0.TimestampField = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		sp0.TimestampField = tmp
	default:
		sp0.TimestampField = c9.Time
	}

	if c10.Valid {
		tmp := c10.V
		sp0.UbigintField = tmp
	}

	if c11.Valid {
		tmp := uint32(c11.Int64)
		sp0.UintegerField = tmp
	}

	if c12.Valid {
		if uid, err := uuid.FromBytes([]byte(c12.String)); err != nil {
			return err
		} else {
			sp0.UUIDField = uid.String()
		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example1ScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example1ScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example1ScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewExample1ScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewExample1ScannerStaticRow(row *sql.Row) Example1ScannerStaticRow {
	return Example1ScannerStaticRow{
		row: row,
	}
}

// Example1ScannerStaticRow generated by genieql
type Example1ScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t Example1ScannerStaticRow) Scan(sp0 *Example1) error {
	var (
		c0  sql.NullInt64
		c1  sql.NullBool
		c2  []byte
		c3  sql.NullFloat64
		c4  sql.NullInt16
		c5  sql.NullInt32
		c6  sql.NullFloat64
		c7  sql.NullInt16
		c8  sql.NullString
		c9  ducktype.NullTime
		c10 ducktype.NullUint64
		c11 sql.NullInt64
		c12 sql.NullString
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0, &c1, &c2, &c3, &c4, &c5, &c6, &c7, &c8, &c9, &c10, &c11, &c12); err != nil {
		return err
	}

	if c0.Valid {
		tmp := int64(c0.Int64)
		sp0.BigintField = tmp
	}

	if c1.Valid {
		tmp := c1.Bool
		sp0.BoolField = tmp
	}

	sp0.ByteArrayField = c2

	if c3.Valid {
		tmp := float64(c3.Float64)
		sp0.DoublePrecisionField = tmp
	}

	if c4.Valid {
		tmp := int16(c4.Int16)
		sp0.Int2Field = tmp
	}

	if c5.Valid {
		tmp := int32(c5.Int32)
		sp0.IntField = tmp
	}

	if c6.Valid {
		tmp := float32(c6.Float64)
		sp0.RealField = tmp
	}

	if c7.Valid {
		tmp := int16(c7.Int16)
		sp0.SmallintField = tmp
	}

	if c8.Valid {
		tmp := string(c8.String)
		sp0.TextField = tmp
	}

	switch c9.InfinityModifier {
	case ducktype.Infinity:
		tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
		sp0.TimestampField = tmp
	case ducktype.NegativeInfinity:
		tmp := time.Unix(math.MinInt64, math.MinInt64)
		sp0.TimestampField = tmp
	default:
		sp0.TimestampField = c9.Time
	}

	if c10.Valid {
		tmp := c10.V
		sp0.UbigintField = tmp
	}

	if c11.Valid {
		tmp := uint32(c11.Int64)
		sp0.UintegerField = tmp
	}

	if c12.Valid {
		if uid, err := uuid.FromBytes([]byte(c12.String)); err != nil {
			return err
		} else {
			sp0.UUIDField = uid.String()
		}
	}

	return nil
}

// Err set an error to return by scan
func (t Example1ScannerStaticRow) Err(err error) Example1ScannerStaticRow {
	t.err = err
	return t
}

// NewExample1ScannerDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewExample1ScannerDynamic(rows *sql.Rows, err error) Example1Scanner {
	if err != nil {
		return errExample1Scanner{e: err}
	}

	return example1ScannerDynamic{
		Rows: rows,
	}
}

// example1ScannerDynamic generated by genieql
type example1ScannerDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t example1ScannerDynamic) Scan(sp0 *Example1) error {
	const (
		cn0  = "bigint_field"
		cn1  = "bool_field"
		cn2  = "byte_array_field"
		cn3  = "double_precision_field"
		cn4  = "int2_field"
		cn5  = "int_field"
		cn6  = "real_field"
		cn7  = "smallint_field"
		cn8  = "text_field"
		cn9  = "timestamp_field"
		cn10 = "ubigint_field"
		cn11 = "uinteger_field"
		cn12 = "uuid_field"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      sql.NullInt64
		c1      sql.NullBool
		c2      []byte
		c3      sql.NullFloat64
		c4      sql.NullInt16
		c5      sql.NullInt32
		c6      sql.NullFloat64
		c7      sql.NullInt16
		c8      sql.NullString
		c9      ducktype.NullTime
		c10     ducktype.NullUint64
		c11     sql.NullInt64
		c12     sql.NullString
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		case cn1:
			dst = append(dst, &c1)
		case cn2:
			dst = append(dst, &c2)
		case cn3:
			dst = append(dst, &c3)
		case cn4:
			dst = append(dst, &c4)
		case cn5:
			dst = append(dst, &c5)
		case cn6:
			dst = append(dst, &c6)
		case cn7:
			dst = append(dst, &c7)
		case cn8:
			dst = append(dst, &c8)
		case cn9:
			dst = append(dst, &c9)
		case cn10:
			dst = append(dst, &c10)
		case cn11:
			dst = append(dst, &c11)
		case cn12:
			dst = append(dst, &c12)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if c0.Valid {
				tmp := int64(c0.Int64)
				sp0.BigintField = tmp
			}

		case cn1:
			if c1.Valid {
				tmp := c1.Bool
				sp0.BoolField = tmp
			}

		case cn2:
			sp0.ByteArrayField = c2

		case cn3:
			if c3.Valid {
				tmp := float64(c3.Float64)
				sp0.DoublePrecisionField = tmp
			}

		case cn4:
			if c4.Valid {
				tmp := int16(c4.Int16)
				sp0.Int2Field = tmp
			}

		case cn5:
			if c5.Valid {
				tmp := int32(c5.Int32)
				sp0.IntField = tmp
			}

		case cn6:
			if c6.Valid {
				tmp := float32(c6.Float64)
				sp0.RealField = tmp
			}

		case cn7:
			if c7.Valid {
				tmp := int16(c7.Int16)
				sp0.SmallintField = tmp
			}

		case cn8:
			if c8.Valid {
				tmp := string(c8.String)
				sp0.TextField = tmp
			}

		case cn9:
			switch c9.InfinityModifier {
			case ducktype.Infinity:
				tmp := time.Unix(math.MaxInt64-62135596800, 999999999)
				sp0.TimestampField = tmp
			case ducktype.NegativeInfinity:
				tmp := time.Unix(math.MinInt64, math.MinInt64)
				sp0.TimestampField = tmp
			default:
				sp0.TimestampField = c9.Time
			}

		case cn10:
			if c10.Valid {
				tmp := c10.V
				sp0.UbigintField = tmp
			}

		case cn11:
			if c11.Valid {
				tmp := uint32(c11.Int64)
				sp0.UintegerField = tmp
			}

		case cn12:
			if c12.Valid {
				if uid, err := uuid.FromBytes([]byte(c12.String)); err != nil {
					return err
				} else {
					sp0.UUIDField = uid.String()
				}
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t example1ScannerDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t example1ScannerDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t example1ScannerDynamic) Next() bool {
	return t.Rows.Next()
}

// Example1FindByBigintField generated by genieql
func Example1FindByBigintField(ctx context.Context, q sqlx.Queryer, c sql.NullInt64) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "bigint_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByBoolField generated by genieql
func Example1FindByBoolField(ctx context.Context, q sqlx.Queryer, c sql.NullBool) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "bool_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByByteArrayField generated by genieql
func Example1FindByByteArrayField(ctx context.Context, q sqlx.Queryer, c []byte) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "byte_array_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByDoublePrecisionField generated by genieql
func Example1FindByDoublePrecisionField(ctx context.Context, q sqlx.Queryer, c sql.NullFloat64) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "double_precision_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByInt2Field generated by genieql
func Example1FindByInt2Field(ctx context.Context, q sqlx.Queryer, c sql.NullInt16) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "int2_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByIntField generated by genieql
func Example1FindByIntField(ctx context.Context, q sqlx.Queryer, c sql.NullInt32) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "int_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByRealField generated by genieql
func Example1FindByRealField(ctx context.Context, q sqlx.Queryer, c sql.NullFloat64) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "real_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindBySmallintField generated by genieql
func Example1FindBySmallintField(ctx context.Context, q sqlx.Queryer, c sql.NullInt16) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "smallint_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByTextField generated by genieql
func Example1FindByTextField(ctx context.Context, q sqlx.Queryer, c sql.NullString) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "text_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByTimestampField generated by genieql
func Example1FindByTimestampField(ctx context.Context, q sqlx.Queryer, c ducktype.NullTime) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "timestamp_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByUbigintField generated by genieql
func Example1FindByUbigintField(ctx context.Context, q sqlx.Queryer, c ducktype.NullUint64) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "ubigint_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByUintegerField generated by genieql
func Example1FindByUintegerField(ctx context.Context, q sqlx.Queryer, c sql.NullInt64) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "uinteger_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1FindByUUIDField generated by genieql
func Example1FindByUUIDField(ctx context.Context, q sqlx.Queryer, c sql.NullString) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM "example1" WHERE "uuid_field" = $1`
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c))
}

// Example1InsertStaticColumns generated by genieql
const Example1InsertStaticColumns = `$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13`

// Example1InsertExplode generated by genieql
func Example1InsertExplode(e *Example1) ([]interface{}, error) {
	var (
		c0  sql.NullInt64       // bigint_field
		c1  sql.NullBool        // bool_field
		c2  []byte              // byte_array_field
		c3  sql.NullFloat64     // double_precision_field
		c4  sql.NullInt16       // int2_field
		c5  sql.NullInt32       // int_field
		c6  sql.NullFloat64     // real_field
		c7  sql.NullInt16       // smallint_field
		c8  sql.NullString      // text_field
		c9  ducktype.NullTime   // timestamp_field
		c10 ducktype.NullUint64 // ubigint_field
		c11 sql.NullInt64       // uinteger_field
		c12 sql.NullString      // uuid_field
	)

	c0.Valid = true
	c0.Int64 = int64(e.BigintField)

	c1.Valid = true
	c1.Bool = e.BoolField

	c2 = e.ByteArrayField

	c3.Valid = true
	c3.Float64 = float64(e.DoublePrecisionField)

	c4.Valid = true
	c4.Int16 = int16(e.Int2Field)

	c5.Valid = true
	c5.Int32 = int32(e.IntField)

	c6.Valid = true
	c6.Float64 = float64(e.RealField)

	c7.Valid = true
	c7.Int16 = int16(e.SmallintField)

	c8.Valid = true
	c8.String = e.TextField

	switch ts := e.TimestampField; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c9.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c9.NegativeInfinity()
	default:
		c9.Status = ducktype.Present
		c9.Time = e.TimestampField
	}

	c10.Valid = true
	c10.V = e.UbigintField

	c11.Valid = true
	c11.Int64 = int64(e.UintegerField)

	c12.Valid = true
	c12.String = e.UUIDField

	return []interface{}{c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12}, nil
}

// Example1Insert generated by genieql
// insert a single example1 record.
func Example1Insert(ctx context.Context, q sqlx.Queryer, e Example1) Example1ScannerStaticRow {
	const query = `INSERT INTO "example1" ("bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field"`
	var (
		c0  sql.NullInt64       // bigint_field
		c1  sql.NullBool        // bool_field
		c2  []byte              // byte_array_field
		c3  sql.NullFloat64     // double_precision_field
		c4  sql.NullInt16       // int2_field
		c5  sql.NullInt32       // int_field
		c6  sql.NullFloat64     // real_field
		c7  sql.NullInt16       // smallint_field
		c8  sql.NullString      // text_field
		c9  ducktype.NullTime   // timestamp_field
		c10 ducktype.NullUint64 // ubigint_field
		c11 sql.NullInt64       // uinteger_field
		c12 sql.NullString
	)
	c0.Valid = true
	c0.Int64 = int64(e.BigintField)
	c1.Valid = true
	c1.Bool = e.BoolField
	c2 = e.ByteArrayField
	c3.Valid = true
	c3.Float64 = float64(e.DoublePrecisionField)
	c4.Valid = true
	c4.Int16 = int16(e.Int2Field)
	c5.Valid = true
	c5.Int32 = int32(e.IntField)
	c6.Valid = true
	c6.Float64 = float64(e.RealField)
	c7.Valid = true
	c7.Int16 = int16(e.SmallintField)
	c8.Valid = true
	c8.String = e.TextField
	switch ts := e.TimestampField; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c9.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c9.NegativeInfinity()
	default:
		c9.Status = ducktype.Present
		c9.Time = e.TimestampField
	}
	c10.Valid = true
	c10.V = e.UbigintField
	c11.Valid = true
	c11.Int64 = int64(e.UintegerField)
	c12.Valid = true
	c12.String = e.UUIDField // uuid_field
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12))
}

// Example1FindByID generated by genieql
func Example1FindByID(ctx context.Context, q sqlx.Queryer, id string) Example1ScannerStaticRow {
	const query = `SELECT "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field" FROM example1 WHERE "uuid_field" = $1`
	var c0 sql.NullString // id
	c0.Valid = true
	c0.String = id
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}

// Example1UpdateTime generated by genieql
func Example1UpdateTime(
	ctx context.Context, q sqlx.
		Queryer, e Example1) Example1ScannerStaticRow {
	const query = `UPDATE example1 SET timestamp_field = $1 RETURNING "bigint_field","bool_field","byte_array_field","double_precision_field","int2_field","int_field","real_field","smallint_field","text_field","timestamp_field","ubigint_field","uinteger_field","uuid_field"`
	var c0 ducktype.NullTime // timestamp_field
	switch ts := e.TimestampField; {
	case time.Unix(math.MaxInt64-62135596800, 999999999).Equal(ts):
		c0.Infinity()
	case time.Unix(math.MinInt64, math.MinInt64).Equal(ts):
		c0.NegativeInfinity()
	default:
		c0.Status = ducktype.Present
		c0.Time = e.TimestampField
	}
	return NewExample1ScannerStaticRow(q.QueryRowContext(ctx, query, c0))
}
