//go:build !genieql.ignore
// +build !genieql.ignore

package autocompile

// DO NOT EDIT: This File was auto generated by the following command:
// genieql auto -o genieql.gen.go
// invoked by go generate @ autocompile/genieql.cmd.go line 3
