package query

import "database/sql"

// DO NOT MODIFY: This File was auto generated by the following command:
// genieql scanner query-literal --output=example_query_literal.gen.go example query
// invoked by go generate @ query/example.go line 8

// ExampleQueryScannerStaticColumns generated by genieql
const ExampleQueryScannerStaticColumns = ``

// NewExampleQueryScannerStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewExampleQueryScannerStatic(rows *sql.Rows, err error) ExampleScanner {
	if err != nil {
		return errExampleScanner{e: err}
	}

	return exampleQueryScannerStatic{
		Rows: rows,
	}
}

// exampleQueryScannerStatic generated by genieql
type exampleQueryScannerStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t exampleQueryScannerStatic) Scan(arg0 *example) error {
	var ()

	if err := t.Rows.Scan(); err != nil {
		return err
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t exampleQueryScannerStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t exampleQueryScannerStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t exampleQueryScannerStatic) Next() bool {
	return t.Rows.Next()
}

// NewExampleQueryScannerStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewExampleQueryScannerStaticRow(row *sql.Row, err error) ExampleQueryScannerStaticRow {
	return ExampleQueryScannerStaticRow{
		err: err,
		row: row,
	}
}

// ExampleQueryScannerStaticRow generated by genieql
type ExampleQueryScannerStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t ExampleQueryScannerStaticRow) Scan(arg0 *example) error {
	var ()

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(); err != nil {
		return err
	}

	return nil
}
