package drivers

import (
	"bitbucket.org/jatone/genieql"
	"github.com/jackc/pgtype"
)

// implements the pgx driver https://github.com/jackc/pgx
func init() {
	genieql.RegisterDriver(PGX, NewDriver(pgx...))
}

// PGX - driver for github.com/jackc/pgx
const PGX = "github.com/jackc/pgx"

const defaultDecode = `func() {
	if err := {{ .From | expr }}.AssignTo({{.To | dereference | expr}}); err != nil {
		return err
	}
}`

var pgx = []genieql.NullableTypeDefinition{
	// cannot support OID yet... due to no field to access.
	// {Type: "pgtype.OID", Native: stringExprString, NullType: "pgtype.OIDValue", NullField: "Text"}
	{
		Type:      "pgtype.CIDR",
		Native:    cidrExpr,
		NullType:  "pgtype.CIDR",
		NullField: "IPNet",
		Decoder:   &pgtype.Inet{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.CIDRArray",
		Native:    cidrArrayExpr,
		NullType:  "pgtype.CIDRArray",
		NullField: "Elements",
		Decoder:   &pgtype.CIDRArray{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Macaddr",
		Native:    macExpr,
		NullType:  "pgtype.Macaddr",
		NullField: "Addr",
		Decoder:   &pgtype.Macaddr{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Name",
		Native:    stringExprString,
		NullType:  "pgtype.Name",
		NullField: "Text",
		Decoder:   &pgtype.Name{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Inet",
		Native:    ipExpr,
		NullType:  "pgtype.Inet",
		NullField: "IPNet",
		Decoder:   &pgtype.Inet{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Numeric",
		Native:    float64ExprString,
		NullType:  "pgtype.Numeric",
		NullField: "Int",
		Decoder:   &pgtype.Numeric{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Bytea",
		Native:    bytesExpr,
		NullType:  "pgtype.Bytea",
		NullField: "Bytes",
		Decoder:   &pgtype.Bytea{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Bit",
		Native:    bytesExpr,
		NullType:  "pgtype.Bit",
		NullField: "Bytes",
		Decoder:   &pgtype.Bit{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Varbit",
		Native:    bytesExpr,
		NullType:  "pgtype.Varbit",
		NullField: "Bytes",
		Decoder:   &pgtype.Varbit{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Bool",
		Native:    boolExprString,
		NullType:  "pgtype.Bool",
		NullField: "Bool",
		Decoder:   &pgtype.Bool{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Float4",
		Native:    float32ExprString,
		NullType:  "pgtype.Float4",
		NullField: "Float",
		Decoder:   &pgtype.Float4{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Float8",
		Native:    float64ExprString,
		NullType:  "pgtype.Float8",
		NullField: "Float",
		Decoder:   &pgtype.Float8{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int2",
		Native:    int16ExprString,
		NullType:  "pgtype.Int2",
		NullField: "Int",
		Decoder:   &pgtype.Int2{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int2Array",
		Native:    intArrExpr,
		NullType:  "pgtype.Int2Array",
		NullField: "Elements",
		Decoder:   &pgtype.Int2Array{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int4",
		Native:    int32ExprString,
		NullType:  "pgtype.Int4",
		NullField: "Int",
		Decoder:   &pgtype.Int4{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int4Array",
		Native:    intArrExpr,
		NullType:  "pgtype.Int4Array",
		NullField: "Elements",
		Decoder:   &pgtype.Int4Array{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int8",
		Native:    int64ExprString,
		NullType:  "pgtype.Int8",
		NullField: "Int",
		Decoder:   &pgtype.Int8{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Int8Array",
		Native:    intArrExpr,
		NullType:  "pgtype.Int8Array",
		NullField: "Elements",
		Decoder:   &pgtype.Int8Array{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Text",
		Native:    stringExprString,
		NullType:  "pgtype.Text",
		NullField: "String",
		Decoder:   &pgtype.Text{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Varchar",
		Native:    stringExprString,
		NullType:  "pgtype.Varchar",
		NullField: "String",
		Decoder:   &pgtype.Varchar{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.BPChar",
		Native:    stringExprString,
		NullType:  "pgtype.BPChar",
		NullField: "String",
		Decoder:   &pgtype.BPChar{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Date",
		Native:    timeExprString,
		NullType:  "pgtype.Date",
		NullField: "Time",
		Decoder:   &pgtype.Date{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Timestamp",
		Native:    timeExprString,
		NullType:  "pgtype.Timestamp",
		NullField: "Time",
		Decoder:   &pgtype.Timestamp{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Timestamptz",
		Native:    timeExprString,
		NullType:  "pgtype.Timestamptz",
		NullField: "Time",
		Decoder:   &pgtype.Timestamptz{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.Interval",
		Native:    durationExpr,
		NullType:  "pgtype.Interval",
		NullField: "Microseconds",
		Decoder:   &pgtype.Interval{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.UUID",
		Native:    stringExprString,
		NullType:  "pgtype.UUID",
		NullField: "Bytes",
		Decoder:   &pgtype.UUID{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.UUIDArray",
		Native:    stringArrExpr,
		NullType:  "pgtype.UUIDArray",
		NullField: "Elements",
		Decoder:   &pgtype.UUIDArray{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.JSONB",
		Native:    bytesExpr,
		NullType:  "pgtype.JSONB",
		NullField: "Bytes",
		Decoder:   &pgtype.JSONB{},
		Decode:    defaultDecode,
	},
	{
		Type:      "pgtype.JSON",
		Native:    bytesExpr,
		NullType:  "pgtype.JSON",
		NullField: "Bytes",
		Decoder:   &pgtype.JSON{},
		Decode:    defaultDecode,
	},
	{
		Type:      "json.RawMessage",
		Native:    bytesExpr,
		NullType:  "pgtype.JSON",
		NullField: "Bytes",
		Decoder:   &pgtype.JSON{},
		Decode:    defaultDecode,
	},
	{
		Type:      "*json.RawMessage",
		Native:    bytesExpr,
		NullType:  "pgtype.JSON",
		NullField: "Bytes",
		Decoder:   &pgtype.JSON{},
		Decode:    defaultDecode,
	},
	{
		Type:      "net.IPNet",
		Native:    cidrExpr,
		NullType:  "pgtype.CIDR",
		NullField: "IPNet",
		Decoder:   &pgtype.Inet{},
		Decode:    defaultDecode,
	},
	{
		Type:      "*net.IPNet",
		Native:    cidrExpr,
		NullType:  "pgtype.CIDR",
		NullField: "IPNet",
		Decoder:   &pgtype.Inet{},
		Decode:    defaultDecode,
	},
	{
		Type:      "[]net.IPNet",
		Native:    cidrArrayExpr,
		NullType:  "pgtype.CIDRArray",
		NullField: "Elements",
		Decoder:   &pgtype.CIDRArray{},
		Decode:    defaultDecode,
	},
	{
		Type:      "*[]net.IPNet",
		Native:    cidrArrayExpr,
		NullType:  "pgtype.CIDRArray",
		NullField: "Elements",
		Decoder:   &pgtype.CIDRArray{},
		Decode:    defaultDecode,
	},
}
