package example

import "database/sql"

// PrivateInt scanner interface.
type PrivateInt interface {
	Scan(arg *int) error
	Next() bool
	Close() error
	Err() error
}

type errPrivateInt struct {
	e error
}

func (t errPrivateInt) Scan(arg *int) error {
	return t.e
}

func (t errPrivateInt) Next() bool {
	return false
}

func (t errPrivateInt) Err() error {
	return t.e
}

func (t errPrivateInt) Close() error {
	return nil
}

// PrivateIntStaticColumns generated by genieql
const PrivateIntStaticColumns = `arg`

// NewPrivateIntStatic creates a scanner that operates on a static
// set of columns that are always returned in the same order.
func NewPrivateIntStatic(rows *sql.Rows, err error) PrivateInt {
	if err != nil {
		return errPrivateInt{e: err}
	}

	return privateIntStatic{
		Rows: rows,
	}
}

// privateIntStatic generated by genieql
type privateIntStatic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t privateIntStatic) Scan(arg *int) error {
	var (
		c0 sql.NullInt64
	)

	if err := t.Rows.Scan(&c0); err != nil {
		return err
	}

	if c0.Valid {
		tmp := int(c0.Int64)
		*arg = tmp
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t privateIntStatic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t privateIntStatic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t privateIntStatic) Next() bool {
	return t.Rows.Next()
}

// NewPrivateIntStaticRow creates a scanner that operates on a static
// set of columns that are always returned in the same order, only scans a single row.
func NewPrivateIntStaticRow(row *sql.Row) PrivateIntStaticRow {
	return PrivateIntStaticRow{
		row: row,
	}
}

// PrivateIntStaticRow generated by genieql
type PrivateIntStaticRow struct {
	err error
	row *sql.Row
}

// Scan generated by genieql
func (t PrivateIntStaticRow) Scan(arg *int) error {
	var (
		c0 sql.NullInt64
	)

	if t.err != nil {
		return t.err
	}

	if err := t.row.Scan(&c0); err != nil {
		return err
	}

	if c0.Valid {
		tmp := int(c0.Int64)
		*arg = tmp
	}

	return nil
}

// Err set an error to return by scan
func (t PrivateIntStaticRow) Err(err error) PrivateIntStaticRow {
	t.err = err
	return t
}

// NewPrivateIntDynamic creates a scanner that operates on a dynamic
// set of columns that can be returned in any subset/order.
func NewPrivateIntDynamic(rows *sql.Rows, err error) PrivateInt {
	if err != nil {
		return errPrivateInt{e: err}
	}

	return privateIntDynamic{
		Rows: rows,
	}
}

// privateIntDynamic generated by genieql
type privateIntDynamic struct {
	Rows *sql.Rows
}

// Scan generated by genieql
func (t privateIntDynamic) Scan(arg *int) error {
	const (
		cn0 = "arg"
	)
	var (
		ignored sql.RawBytes
		err     error
		columns []string
		dst     []interface{}
		c0      sql.NullInt64
	)

	if columns, err = t.Rows.Columns(); err != nil {
		return err
	}

	dst = make([]interface{}, 0, len(columns))

	for _, column := range columns {
		switch column {
		case cn0:
			dst = append(dst, &c0)
		default:
			dst = append(dst, &ignored)
		}
	}

	if err := t.Rows.Scan(dst...); err != nil {
		return err
	}

	for _, column := range columns {
		switch column {
		case cn0:
			if c0.Valid {
				tmp := int(c0.Int64)
				*arg = tmp
			}

		}
	}

	return t.Rows.Err()
}

// Err generated by genieql
func (t privateIntDynamic) Err() error {
	return t.Rows.Err()
}

// Close generated by genieql
func (t privateIntDynamic) Close() error {
	if t.Rows == nil {
		return nil
	}
	return t.Rows.Close()
}

// Next generated by genieql
func (t privateIntDynamic) Next() bool {
	return t.Rows.Next()
}
