//go:build !genieql.ignore
// +build !genieql.ignore

package pkga

import (
	"net"
	"time"
)

// DO NOT EDIT: This File was auto generated by the following command:
// genieql -test.paniconexit0 -test.timeout=10m0s -test.run=TestAutoCompileGraph_Integration_ThreeLevelDependencies

// PackageAExample generated by genieql
type PackageAExample struct {
	BigintField          int
	BitField             []byte
	BitVaryingField      []byte
	BoolField            bool
	ByteArrayField       []byte
	CharacterField       string
	CharacterFixedField  string
	CidrField            net.IPNet
	DecimalField         float64
	DoublePrecisionField float64
	InetField            net.IP
	Int2Array            []int
	Int4Array            []int
	Int8Array            []int
	IntField             int
	IntervalField        time.Duration
	JSONField            []byte
	JsonbField           []byte
	MacaddrField         net.HardwareAddr
	NumericField         float64
	RealField            float32
	SmallintField        int
	TextField            string
	TimestampField       time.Time
	UUIDArray            []string
	UUIDField            string
}


